
nodes = [
	{:hostname => "web-proxy", :cpus => 1, :mem => 512, :ip => "10.10.10.10", :prov_script => "web-proxy.sh"},
	{:hostname => "web-1", :cpus => 1, :mem => 512, :ip => "10.10.10.11", :prov_script => "web-1.sh"},
	{:hostname => "web-2", :cpus => 1, :mem => 512, :ip => "10.10.10.12", :prov_script => "web-2.sh"},
	{:hostname => "client", :cpus => 1, :mem => 512, :ip => "10.10.10.13", :prov_script => "client.sh"}
]

Vagrant.configure(2) do |config|
	nodes.each do |node|
		config.vm.define node[:hostname] do |vmachine|
			vmachine.vm.box_download_insecure = true
			vmachine.vm.box = "ubuntu/focal64"
			vmachine.vm.box_check_update = false
			vmachine.vm.hostname = node[:hostname]
			vmachine.vm.network "private_network", ip: node[:ip], virtualbox__intnet: true
			vmachine.vm.provider :virtualbox do |domain|
				domain.memory = node[:mem]
				domain.cpus = node[:cpus]
			end
			#vmachine.vm.provision :shell, path: node[:prov_script]
		end
	end
end
