
nodes = [
	{:hostname => "web-1", :cpus => 1, :mem => 512},
	{:hostname => "web-2", :cpus => 1, :mem => 512},
	{:hostname => "web-proxy", :cpus => 1, :mem => 512}
]


Vagrant.configure(2) do |config|
	nodes.each do |node|
		config.vm.define node[:hostname] do |vmachine|
			vmachine.vm.box_download_insecure = true
			vmachine.vm.box = "ubuntu/focal64"
			vmachine.vm.box_check_update = false
			vmachine.vm.hostname = node[:hostname]
			vmachine.vm.provider :virtualbox do |domain|
				domain.memory = node[:mem]
				domain.cpus = node[:cpus]
			end
		end
	end
end
